import React, { useState } from "react";
import { ChevronDown, ChevronUp, Info } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { AdAnalysis } from "@/app/actions/geminiAi";

interface KeywordAnalysisTableProps {
  data: AdAnalysis;
  isLoading: boolean;
  error: string | null;
}

const KeywordAnalysisTable: React.FC<KeywordAnalysisTableProps> = ({
  data,
  isLoading,
  error,
}) => {
  const [expanded, setExpanded] = useState(false);

  if (isLoading) {
    return <div>Analyzing keywords...</div>;
  }

  if (error) {
    return <div>Error: {error}</div>;
  }

  if (!data) {
    return <div>No keyword data available</div>;
  }
  const analysis = data as AdAnalysis;

  const displayCount = expanded
    ? Math.max(data.topKeywords.length, data.longTailKeywords.length)
    : 5;

  const InsightItem = ({ label, value }) => (
    <div className="text-sm">
      <span className="font-medium text-gray-700">{label}:</span>{" "}
      <span className="text-gray-800">{value || "Not specified"}</span>
    </div>
  );

  return (
    <div className="space-y-4">
      <div className="space-y-3 rounded-lg bg-gray-50 p-4">
        <h3 className="mb-2 flex items-center text-lg font-semibold">
          AI-Powered Ad Insights
          <Info className="ml-2 h-4 w-4 text-gray-500" />
        </h3>

        <div className="grid grid-cols-2 gap-3">
          <InsightItem
            label="Target Gender"
            value={data.genderTarget.join(", ")}
          />
          <InsightItem
            label="Target Age Range"
            value={data.ageTarget.join(", ")}
          />
          <InsightItem label="Budget Level" value={data.estimatedBudget} />
          <InsightItem
            label="Ad Categories"
            value={data.adCategories.join(", ")}
          />
          <InsightItem
            label="Target Audience"
            value={data.targetAudience.join(", ")}
          />
          <InsightItem
            label="Ad Objectives"
            value={data.adObjective.join(", ")}
          />
        </div>

        <p className="mt-2 text-sm text-gray-600">
          These insights are generated by our advanced AI analysis of the ad
          content. While highly accurate, they represent our best interpretation
          and may not exactly match the advertiser's internal strategy.
        </p>
      </div>

      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[45%]">Top Focus Keywords</TableHead>
            <TableHead className="w-[10%]">Count</TableHead>
            <TableHead className="w-[35%]">Long-Tail Keywords</TableHead>
            <TableHead className="w-[10%]">Count</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {Array.from({ length: displayCount }).map((_, index) => (
            <TableRow key={index}>
              <TableCell className="max-w-[200px] truncate">
                {data.topKeywords[index]?.word || ""}
              </TableCell>
              <TableCell>{data.topKeywords[index]?.count || ""}</TableCell>
              <TableCell className="max-w-[200px] truncate">
                {data.longTailKeywords[index]?.phrase || ""}
              </TableCell>
              <TableCell>{data.longTailKeywords[index]?.count || ""}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      {Math.max(data.topKeywords.length, data.longTailKeywords.length) > 5 && (
        <Button
          onClick={() => setExpanded(!expanded)}
          variant="outline"
          className="w-full"
        >
          {expanded ? (
            <>
              Show Less <ChevronUp className="ml-2 h-4 w-4" />
            </>
          ) : (
            <>
              Show More <ChevronDown className="ml-2 h-4 w-4" />
            </>
          )}
        </Button>
      )}
    </div>
  );
};

export default KeywordAnalysisTable;
