// @/lib/countryCodesAlpha2Flag.ts

export const countryCodesAlpha2Flag = [
  //{ value: "ALL", label: "All Countries", icon: "/flags/un.svg" },
  { value: "BR", label: "Brazil", icon: "/flags/br.svg" },
  { value: "IN", label: "India", icon: "/flags/in.svg" },
  { value: "GB", label: "United Kingdom", icon: "/flags/gb.svg" },
  { value: "US", label: "United States", icon: "/flags/us.svg" },
  { value: "CA", label: "Canada", icon: "/flags/ca.svg" },
  { value: "AR", label: "Argentina", icon: "/flags/ar.svg" },
  { value: "AU", label: "Australia", icon: "/flags/au.svg" },
  { value: "AT", label: "Austria", icon: "/flags/at.svg" },
  { value: "BE", label: "Belgium", icon: "/flags/be.svg" },
  { value: "CL", label: "Chile", icon: "/flags/cl.svg" },
  { value: "CN", label: "China", icon: "/flags/cn.svg" },
  { value: "CO", label: "Colombia", icon: "/flags/co.svg" },
  { value: "HR", label: "Croatia", icon: "/flags/hr.svg" },
  { value: "DK", label: "Denmark", icon: "/flags/dk.svg" },
  { value: "DO", label: "Dominican Republic", icon: "/flags/do.svg" },
  { value: "EG", label: "Egypt", icon: "/flags/eg.svg" },
  { value: "FI", label: "Finland", icon: "/flags/fi.svg" },
  { value: "FR", label: "France", icon: "/flags/fr.svg" },
  { value: "DE", label: "Germany", icon: "/flags/de.svg" },
  { value: "GR", label: "Greece", icon: "/flags/gr.svg" },
  { value: "HK", label: "Hong Kong", icon: "/flags/hk.svg" },
  { value: "ID", label: "Indonesia", icon: "/flags/id.svg" },
  { value: "IE", label: "Ireland", icon: "/flags/ie.svg" },
  {
    value: "IL",
    label: "Israel",
    icon: "/flags/ps.svg", //there is no israel X_X , it's an Occupied Palestinian Territory by a group of WAR Criminals  "/flags/il.svg"
  },
  { value: "IT", label: "Italy", icon: "/flags/it.svg" },
  { value: "JP", label: "Japan", icon: "/flags/jp.svg" },
  { value: "JO", label: "Jordan", icon: "/flags/jo.svg" },
  { value: "KW", label: "Kuwait", icon: "/flags/kw.svg" },
  { value: "LB", label: "Lebanon", icon: "/flags/lb.svg" },
  { value: "MY", label: "Malaysia", icon: "/flags/my.svg" },
  { value: "MX", label: "Mexico", icon: "/flags/mx.svg" },
  { value: "NL", label: "Netherlands", icon: "/flags/nl.svg" },
  { value: "NZ", label: "New Zealand", icon: "/flags/nz.svg" },
  { value: "NG", label: "Nigeria", icon: "/flags/ng.svg" },
  { value: "NO", label: "Norway", icon: "/flags/no.svg" },
  { value: "PK", label: "Pakistan", icon: "/flags/pk.svg" },
  { value: "PA", label: "Panama", icon: "/flags/pa.svg" },
  { value: "PE", label: "Peru", icon: "/flags/pe.svg" },
  { value: "PH", label: "Philippines", icon: "/flags/ph.svg" },
  { value: "PL", label: "Poland", icon: "/flags/pl.svg" },
  { value: "RU", label: "Russia", icon: "/flags/ru.svg" },
  { value: "SA", label: "Saudi Arabia", icon: "/flags/sa.svg" },
  { value: "RS", label: "Serbia", icon: "/flags/rs.svg" },
  { value: "SG", label: "Singapore", icon: "/flags/sg.svg" },
  { value: "ZA", label: "South Africa", icon: "/flags/za.svg" },
  { value: "KR", label: "South Korea", icon: "/flags/kr.svg" },
  { value: "ES", label: "Spain", icon: "/flags/es.svg" },
  { value: "SE", label: "Sweden", icon: "/flags/se.svg" },
  { value: "CH", label: "Switzerland", icon: "/flags/ch.svg" },
  { value: "TW", label: "Taiwan", icon: "/flags/tw.svg" },
  { value: "TH", label: "Thailand", icon: "/flags/th.svg" },
  { value: "TR", label: "Turkey", icon: "/flags/tr.svg" },
  { value: "AE", label: "United Arab Emirates", icon: "/flags/ae.svg" },
  { value: "VE", label: "Venezuela", icon: "/flags/ve.svg" },
  { value: "PT", label: "Portugal", icon: "/flags/pt.svg" },
  { value: "LU", label: "Luxembourg", icon: "/flags/lu.svg" },
  { value: "BG", label: "Bulgaria", icon: "/flags/bg.svg" },
  { value: "CZ", label: "Czech Republic", icon: "/flags/cz.svg" },
  { value: "SI", label: "Slovenia", icon: "/flags/si.svg" },
  { value: "IS", label: "Iceland", icon: "/flags/is.svg" },
  { value: "SK", label: "Slovakia", icon: "/flags/sk.svg" },
  { value: "LT", label: "Lithuania", icon: "/flags/lt.svg" },
  { value: "TT", label: "Trinidad and Tobago", icon: "/flags/tt.svg" },
  { value: "BD", label: "Bangladesh", icon: "/flags/bd.svg" },
  { value: "LK", label: "Sri Lanka", icon: "/flags/lk.svg" },
  { value: "KE", label: "Kenya", icon: "/flags/ke.svg" },
  { value: "HU", label: "Hungary", icon: "/flags/hu.svg" },
  { value: "MA", label: "Morocco", icon: "/flags/ma.svg" },
  { value: "CY", label: "Cyprus", icon: "/flags/cy.svg" },
  { value: "JM", label: "Jamaica", icon: "/flags/jm.svg" },
  { value: "EC", label: "Ecuador", icon: "/flags/ec.svg" },
  { value: "RO", label: "Romania", icon: "/flags/ro.svg" },
  { value: "BO", label: "Bolivia", icon: "/flags/bo.svg" },
  { value: "GT", label: "Guatemala", icon: "/flags/gt.svg" },
  { value: "CR", label: "Costa Rica", icon: "/flags/cr.svg" },
  { value: "QA", label: "Qatar", icon: "/flags/qa.svg" },
  { value: "SV", label: "El Salvador", icon: "/flags/sv.svg" },
  { value: "HN", label: "Honduras", icon: "/flags/hn.svg" },
  { value: "NI", label: "Nicaragua", icon: "/flags/ni.svg" },
  { value: "PY", label: "Paraguay", icon: "/flags/py.svg" },
  { value: "UY", label: "Uruguay", icon: "/flags/uy.svg" },
  { value: "PR", label: "Puerto Rico", icon: "/flags/pr.svg" },
  { value: "BA", label: "Bosnia and Herzegovina", icon: "/flags/ba.svg" },
  { value: "PS", label: "Palestine", icon: "/flags/ps.svg" },
  { value: "TN", label: "Tunisia", icon: "/flags/tn.svg" },
  { value: "BH", label: "Bahrain", icon: "/flags/bh.svg" },
  { value: "VN", label: "Vietnam", icon: "/flags/vn.svg" },
  { value: "GH", label: "Ghana", icon: "/flags/gh.svg" },
  { value: "MU", label: "Mauritius", icon: "/flags/mu.svg" },
  { value: "UA", label: "Ukraine", icon: "/flags/ua.svg" },
  { value: "MT", label: "Malta", icon: "/flags/mt.svg" },
  { value: "BS", label: "Bahamas", icon: "/flags/bs.svg" },
  { value: "MV", label: "Maldives", icon: "/flags/mv.svg" },
  { value: "OM", label: "Oman", icon: "/flags/om.svg" },
  { value: "MK", label: "North Macedonia", icon: "/flags/mk.svg" },
  { value: "LV", label: "Latvia", icon: "/flags/lv.svg" },
  { value: "EE", label: "Estonia", icon: "/flags/ee.svg" },
  { value: "IQ", label: "Iraq", icon: "/flags/iq.svg" },
  { value: "DZ", label: "Algeria", icon: "/flags/dz.svg" },
  { value: "AL", label: "Albania", icon: "/flags/al.svg" },
  { value: "NP", label: "Nepal", icon: "/flags/np.svg" },
  { value: "MO", label: "Macau", icon: "/flags/mo.svg" },
  { value: "ME", label: "Montenegro", icon: "/flags/me.svg" },
  { value: "SN", label: "Senegal", icon: "/flags/sn.svg" },
  { value: "GE", label: "Georgia", icon: "/flags/ge.svg" },
  { value: "BN", label: "Brunei", icon: "/flags/bn.svg" },
  { value: "UG", label: "Uganda", icon: "/flags/ug.svg" },
  { value: "GP", label: "Guadeloupe", icon: "/flags/gp.svg" },
  { value: "BB", label: "Barbados", icon: "/flags/bb.svg" },
  { value: "AZ", label: "Azerbaijan", icon: "/flags/az.svg" },
  { value: "TZ", label: "Tanzania", icon: "/flags/tz.svg" },
  { value: "LY", label: "Libya", icon: "/flags/ly.svg" },
  { value: "MQ", label: "Martinique", icon: "/flags/mq.svg" },
  { value: "CM", label: "Cameroon", icon: "/flags/cm.svg" },
  { value: "BW", label: "Botswana", icon: "/flags/bw.svg" },
  { value: "ET", label: "Ethiopia", icon: "/flags/et.svg" },
  { value: "KZ", label: "Kazakhstan", icon: "/flags/kz.svg" },
  { value: "NA", label: "Namibia", icon: "/flags/na.svg" },
  { value: "MG", label: "Madagascar", icon: "/flags/mg.svg" },
  { value: "NC", label: "New Caledonia", icon: "/flags/nc.svg" },
  { value: "MD", label: "Moldova", icon: "/flags/md.svg" },
  { value: "FJ", label: "Fiji", icon: "/flags/fj.svg" },
  { value: "BY", label: "Belarus", icon: "/flags/by.svg" },
  { value: "JE", label: "Jersey", icon: "/flags/je.svg" },
  { value: "GU", label: "Guam", icon: "/flags/gu.svg" },
  { value: "YE", label: "Yemen", icon: "/flags/ye.svg" },
  { value: "ZM", label: "Zambia", icon: "/flags/zm.svg" },
  { value: "IM", label: "Isle of Man", icon: "/flags/im.svg" },
  { value: "HT", label: "Haiti", icon: "/flags/ht.svg" },
  { value: "KH", label: "Cambodia", icon: "/flags/kh.svg" },
  { value: "AW", label: "Aruba", icon: "/flags/aw.svg" },
  { value: "PF", label: "French Polynesia", icon: "/flags/pf.svg" },
  { value: "AF", label: "Afghanistan", icon: "/flags/af.svg" },
  { value: "BM", label: "Bermuda", icon: "/flags/bm.svg" },
  { value: "GY", label: "Guyana", icon: "/flags/gy.svg" },
  { value: "AM", label: "Armenia", icon: "/flags/am.svg" },
  { value: "MW", label: "Malawi", icon: "/flags/mw.svg" },
  { value: "AG", label: "Antigua and Barbuda", icon: "/flags/ag.svg" },
  { value: "RW", label: "Rwanda", icon: "/flags/rw.svg" },
  { value: "GG", label: "Guernsey", icon: "/flags/gg.svg" },
  { value: "GM", label: "Gambia", icon: "/flags/gm.svg" },
  { value: "FO", label: "Faroe Islands", icon: "/flags/fo.svg" },
  { value: "LC", label: "Saint Lucia", icon: "/flags/lc.svg" },
  { value: "KY", label: "Cayman Islands", icon: "/flags/ky.svg" },
  { value: "BJ", label: "Benin", icon: "/flags/bj.svg" },
  { value: "AD", label: "Andorra", icon: "/flags/ad.svg" },
  { value: "GD", label: "Grenada", icon: "/flags/gd.svg" },
  { value: "VI", label: "U.S. Virgin Islands", icon: "/flags/vi.svg" },
  { value: "BZ", label: "Belize", icon: "/flags/bz.svg" },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    icon: "/flags/vc.svg",
  },
  { value: "MN", label: "Mongolia", icon: "/flags/mn.svg" },
  { value: "MZ", label: "Mozambique", icon: "/flags/mz.svg" },
  { value: "ML", label: "Mali", icon: "/flags/ml.svg" },
  { value: "AO", label: "Angola", icon: "/flags/ao.svg" },
  { value: "GF", label: "French Guiana", icon: "/flags/gf.svg" },
  { value: "UZ", label: "Uzbekistan", icon: "/flags/uz.svg" },
  { value: "DJ", label: "Djibouti", icon: "/flags/dj.svg" },
  { value: "BF", label: "Burkina Faso", icon: "/flags/bf.svg" },
  { value: "MC", label: "Monaco", icon: "/flags/mc.svg" },
  { value: "TG", label: "Togo", icon: "/flags/tg.svg" },
  { value: "GL", label: "Greenland", icon: "/flags/gl.svg" },
  { value: "GA", label: "Gabon", icon: "/flags/ga.svg" },
  { value: "GI", label: "Gibraltar", icon: "/flags/gi.svg" },
  {
    value: "CD",
    label: "Democratic Republic of the Congo",
    icon: "/flags/cd.svg",
  },
  { value: "KG", label: "Kyrgyzstan", icon: "/flags/kg.svg" },
  { value: "PG", label: "Papua New Guinea", icon: "/flags/pg.svg" },
  { value: "BT", label: "Bhutan", icon: "/flags/bt.svg" },
  { value: "KN", label: "Saint Kitts and Nevis", icon: "/flags/kn.svg" },
  { value: "SZ", label: "Eswatini", icon: "/flags/sz.svg" },
  { value: "LS", label: "Lesotho", icon: "/flags/ls.svg" },
  { value: "LA", label: "Laos", icon: "/flags/la.svg" },
  { value: "LI", label: "Liechtenstein", icon: "/flags/li.svg" },
  { value: "MP", label: "Northern Mariana Islands", icon: "/flags/mp.svg" },
  { value: "SR", label: "Suriname", icon: "/flags/sr.svg" },
  { value: "SC", label: "Seychelles", icon: "/flags/sc.svg" },
  { value: "VG", label: "British Virgin Islands", icon: "/flags/vg.svg" },
  { value: "TC", label: "Turks and Caicos Islands", icon: "/flags/tc.svg" },
  { value: "DM", label: "Dominica", icon: "/flags/dm.svg" },
  { value: "MR", label: "Mauritania", icon: "/flags/mr.svg" },
  { value: "AX", label: "Åland Islands", icon: "/flags/ax.svg" },
  { value: "SM", label: "San Marino", icon: "/flags/sm.svg" },
  { value: "SL", label: "Sierra Leone", icon: "/flags/sl.svg" },
  { value: "NE", label: "Niger", icon: "/flags/ne.svg" },
  { value: "CG", label: "Republic of the Congo", icon: "/flags/cg.svg" },
  { value: "AI", label: "Anguilla", icon: "/flags/ai.svg" },
  { value: "YT", label: "Mayotte", icon: "/flags/yt.svg" },
  { value: "CV", label: "Cape Verde", icon: "/flags/cv.svg" },
  { value: "GN", label: "Guinea", icon: "/flags/gn.svg" },
  { value: "TM", label: "Turkmenistan", icon: "/flags/tm.svg" },
  { value: "BI", label: "Burundi", icon: "/flags/bi.svg" },
  { value: "TJ", label: "Tajikistan", icon: "/flags/tj.svg" },
  { value: "VU", label: "Vanuatu", icon: "/flags/vu.svg" },
  { value: "SB", label: "Solomon Islands", icon: "/flags/sb.svg" },
  { value: "ER", label: "Eritrea", icon: "/flags/er.svg" },
  { value: "WS", label: "Samoa", icon: "/flags/ws.svg" },
  { value: "AS", label: "American Samoa", icon: "/flags/as.svg" },
  { value: "FK", label: "Falkland Islands", icon: "/flags/fk.svg" },
  { value: "GQ", label: "Equatorial Guinea", icon: "/flags/gq.svg" },
  { value: "TO", label: "Tonga", icon: "/flags/to.svg" },
  { value: "KM", label: "Comoros", icon: "/flags/km.svg" },
  { value: "PW", label: "Palau", icon: "/flags/pw.svg" },
  { value: "FM", label: "Micronesia", icon: "/flags/fm.svg" },
  { value: "CF", label: "Central African Republic", icon: "/flags/cf.svg" },
  { value: "SO", label: "Somalia", icon: "/flags/so.svg" },
  { value: "MH", label: "Marshall Islands", icon: "/flags/mh.svg" },
  { value: "VA", label: "Vatican City", icon: "/flags/va.svg" },
  { value: "TD", label: "Chad", icon: "/flags/td.svg" },
  { value: "KI", label: "Kiribati", icon: "/flags/ki.svg" },
  { value: "ST", label: "São Tomé and Príncipe", icon: "/flags/st.svg" },
  { value: "TV", label: "Tuvalu", icon: "/flags/tv.svg" },
  { value: "NR", label: "Nauru", icon: "/flags/nr.svg" },
  { value: "RE", label: "Réunion", icon: "/flags/re.svg" },
  { value: "LR", label: "Liberia", icon: "/flags/lr.svg" },
  { value: "ZW", label: "Zimbabwe", icon: "/flags/zw.svg" },
  { value: "CI", label: "Ivory Coast", icon: "/flags/ci.svg" },
  { value: "MM", label: "Myanmar", icon: "/flags/mm.svg" },
  { value: "AN", label: "Netherlands Antilles", icon: "/flags/an.svg" },
  { value: "AQ", label: "Antarctica", icon: "/flags/aq.svg" },
  { value: "BQ", label: "Caribbean Netherlands", icon: "/flags/bq.svg" },
  { value: "BV", label: "Bouvet Island", icon: "/flags/bv.svg" },
  {
    value: "IO",
    label: "British Indian Ocean Territory",
    icon: "/flags/io.svg",
  },
  { value: "CX", label: "Christmas Island", icon: "/flags/cx.svg" },
  { value: "CC", label: "Cocos (Keeling) Islands", icon: "/flags/cc.svg" },
  { value: "CK", label: "Cook Islands", icon: "/flags/ck.svg" },
  { value: "CW", label: "Curaçao", icon: "/flags/cw.svg" },
  { value: "TF", label: "French Southern Territories", icon: "/flags/tf.svg" },
  { value: "GW", label: "Guinea-Bissau", icon: "/flags/gw.svg" },
  {
    value: "HM",
    label: "Heard Island and McDonald Islands",
    icon: "/flags/hm.svg",
  },
  { value: "XK", label: "Kosovo", icon: "/flags/xk.svg" },
  { value: "MS", label: "Montserrat", icon: "/flags/ms.svg" },
  { value: "NU", label: "Niue", icon: "/flags/nu.svg" },
  { value: "NF", label: "Norfolk Island", icon: "/flags/nf.svg" },
  { value: "PN", label: "Pitcairn Islands", icon: "/flags/pn.svg" },
  { value: "BL", label: "Saint Barthélemy", icon: "/flags/bl.svg" },
  {
    value: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
    icon: "/flags/sh-hl.svg",
  },
  { value: "MF", label: "Saint Martin", icon: "/flags/mf.svg" },
  { value: "PM", label: "Saint Pierre and Miquelon", icon: "/flags/pm.svg" },
  { value: "SX", label: "Sint Maarten", icon: "/flags/sx.svg" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    icon: "/flags/gs.svg",
  },
  { value: "SS", label: "South Sudan", icon: "/flags/ss.svg" },
  { value: "SJ", label: "Svalbard and Jan Mayen", icon: "/flags/sj.svg" },
  { value: "TL", label: "East Timor", icon: "/flags/tl.svg" },
  { value: "TK", label: "Tokelau", icon: "/flags/tk.svg" },
  {
    value: "UM",
    label: "United States Minor Outlying Islands",
    icon: "/flags/us.svg",
  },
  { value: "WF", label: "Wallis and Futuna", icon: "/flags/wf.svg" },
  { value: "EH", label: "Western Sahara", icon: "/flags/eh.svg" },
];
